// Regenerates render/assets/charw8.js: per-character widths (px) of printable
// ASCII at 8pt bold in the document's font stack, measured in Chromium — the
// same engine that lays the PDF out. cell_system sums these to decide which
// font size a customer system id needs to render in full (fleet_page.js).
// Also prints sum-of-chars vs whole-string widths for real ids, so the
// kerning error the sum ignores stays a measured number, not a hope — the
// KERN_MARGIN in fleet_page.js must exceed the worst overshoot shown here.
// Usage: node sme_reports/dev/gen_charw.js
const fs = require("fs");
const path = require("path");
const puppeteer = require("puppeteer");

const PROBES = [
  "45630-1307484",
  "2342574 / SUMMITVCT",
  " CE Tag# 583-01060",
  "Site ID: 400-389405",
  "895936 / 59507378",
  "CE Tag# 400-315634",
  "1656095 / 10363",
  "DI36-122"
];

(async () => {
  const browser = await puppeteer.launch({
    headless: "new",
    args: ["--no-sandbox", "--disable-setuid-sandbox"]
  });
  const page = await browser.newPage();
  const chars = [];
  for (let c = 32; c <= 126; c++) chars.push(String.fromCharCode(c));
  await page.setContent(
    `<body style='font-family: "Helvetica Neue", Helvetica, Arial, sans-serif'>` +
      // Each char measured between sentinels so leading/trailing spaces keep
      // their advance width (a bare " " span measures 0).
      chars
        .map(
          (c, i) =>
            `<div style="font-size:8pt;font-weight:700;white-space:pre"><span id="c${i}">||${c
              .replace(/&/g, "&amp;")
              .replace(/</g, "&lt;")}||</span></div>`
        )
        .join("") +
      `<div style="font-size:8pt;font-weight:700;white-space:pre"><span id="bare">||||</span></div>` +
      PROBES.map(
        (s, i) =>
          `<div style="font-size:8pt;font-weight:700;white-space:pre"><span id="p${i}">${s
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")}</span></div>`
      ).join("") +
      `</body>`
  );
  const w_of = (id) =>
    page.evaluate((id) => document.getElementById(id).getBoundingClientRect().width, id);
  const bare = await w_of("bare");
  const table = {};
  for (let i = 0; i < chars.length; i++)
    table[chars[i]] = Math.round((await w_of(`c${i}`)) * 1000 - bare * 1000) / 1000;

  let worst = 0;
  for (let i = 0; i < PROBES.length; i++) {
    const real = await w_of(`p${i}`);
    const sum = [...PROBES[i]].reduce((n, ch) => n + table[ch], 0);
    worst = Math.max(worst, Math.abs(sum - real));
    console.log(
      `${JSON.stringify(PROBES[i]).padEnd(24)} real ${real.toFixed(1).padStart(6)}  sum ${sum.toFixed(1).padStart(6)}  err ${(sum - real).toFixed(2)}`
    );
  }
  console.log(`worst |err| ${worst.toFixed(2)}px`);
  await browser.close();

  const out = path.join(__dirname, "..", "render", "assets", "charw8.js");
  fs.writeFileSync(
    out,
    `// GENERATED by dev/gen_charw.js — do not edit by hand.\n` +
      `// Px width of each printable ASCII char at 8pt bold, Chromium,\n` +
      `// "Helvetica Neue"/Helvetica/Arial. Scale linearly for other sizes.\n` +
      `module.exports = ${JSON.stringify(table, null, 0)};\n`
  );
  console.log(`wrote ${out}`);
})();
