const pgp = require('pg-promise')();

// HELPER FOR LINKING TO EXTERNAL QUERY FILES
const pg_tables = {
    ge: {
        mm3: new pgp.helpers.TableName({
            table: 'ge_mm3',
            schema: 'mag',
        }),
        mm3_units: new pgp.helpers.TableName({
            table: 'ge_mm3_units',
            schema: 'mag',
        }),
        mm4: new pgp.helpers.TableName({
            table: 'ge_mm4',
            schema: 'mag',
        }),
        mm4_units: new pgp.helpers.TableName({
            table: 'ge_mm4_units',
            schema: 'mag',
        }),
    },
    siemens: {
        default: new pgp.helpers.TableName({
            table: 'siemens',
            schema: 'mag',
        }),
        default_units: new pgp.helpers.TableName({
            table: 'siemens_units',
            schema: 'mag',
        }),
        non_tim: new pgp.helpers.TableName({
            table: 'siemens_non_tim',
            schema: 'mag',
        }),
        non_tim_units: new pgp.helpers.TableName({
            table: 'siemens_non_tim_units',
            schema: 'mag',
        }),
    },
    // philips: new pgp.helpers.TableName({
    //    table: 'philips_mri_monitoring_data_agg',
    //    schema: 'mag',
    // }),
    philips: {
        monitoring_agg: new pgp.helpers.TableName({
            table: 'philips_mri_monitoring_data_agg',
            schema: 'mag',
        }),
        monitoring_units: new pgp.helpers.TableName({
            table: 'philips_mri_monitoring_data_units',
            schema: 'mag',
        }),
    },
    edu: {
        v1: new pgp.helpers.TableName({ table: 'v1', schema: 'edu' }),
        v2: new pgp.helpers.TableName({ table: 'v2', schema: 'edu' }),
        v2_units: new pgp.helpers.TableName({
            table: 'v2_units',
            schema: 'edu',
        }),
    },
    log: {
        philips: {
            mri: new pgp.helpers.TableName({
                table: 'philips_mri_logcurrent',
                schema: 'log',
            }),
            ct_eal_events: new pgp.helpers.TableName({
                table: 'philips_ct_eal_events',
                schema: 'log',
            }),
            cv: new pgp.helpers.TableName({
                table: 'philips_cv_eventlog',
                schema: 'log',
            }),
        },
        siemens: {
            ct: new pgp.helpers.TableName({
                table: 'siemens_ct',
                schema: 'log',
            }),
        },
        ge: {
            ct_gesys: new pgp.helpers.TableName({
                table: 'ge_ct_gesys',
                schema: 'log',
            }),
        },
    },
    alert: {
        detections: new pgp.helpers.TableName({
            table: 'detections',
            schema: 'alert',
        }),
        notifications: new pgp.helpers.TableName({
            table: 'notifications',
            schema: 'alert',
        }),
    },
    util: {
        app_run_logs: new pgp.helpers.TableName({
            table: 'app_run_logs',
            schema: 'util',
        }),
    },
};

const pg_column_sets = {
    alert: {
        detections: new pgp.helpers.ColumnSet(
            [
                'job_id',
                'run_id',
                'alert_model_id',
                'system_id',
                'pg_table',
                'field_name',
                'units_field_name',
                'resolved_field_content',
                'resolved_field_units',
                'operator',
                'threshold',
                'resolved_threshold_content',
                'threshold_units',
                'threshold_offset',
                'severity',
                // 'inserted_at',
                'row_id',
                'field_content',
                'field_name_alias',
                'alert_units',
                'capture_datetime',
                'log_msg',
                'notify_frequency',
            ],
            {
                table: pg_tables.alert.detections,
            }
        ),
        notifications: new pgp.helpers.ColumnSet(
            [
                'job_id',
                'user_id',
                'email_status',
                'sms_status',
                'sms_sid',
                'alert_detection_ids',
                // 'last_update',
                'run_id',
                'customer_id',
                'detected_alert_models',
            ],
            {
                table: pg_tables.alert.notifications,
            }
        ),
    },
    util: {
        app_run_logs: new pgp.helpers.ColumnSet(
            ['app_name', 'run_id', 'verbose_log', 'warn_error_logs'],
            { table: pg_tables.util.app_run_logs }
        ),
    },
    mag: {
        ge: {
            mm3: new pgp.helpers.ColumnSet(
                [
                    // 'id',
                    'capture_datetime',
                    'system_id',
                    'host_date',
                    'host_time',
                    'host_datetime',
                    'he_level_value',
                    'water_flow_value',
                    'water_temp_value',
                    'shield_si410_value',
                    'recon_ruo_value',
                    'recon_si410_value',
                    'coldhead_ruo_value',
                    'he_pressure_value',
                    'cdc1_value',
                    'cs1_value',
                    'ht_value',
                    'hdc_value',
                    'rf_value',
                    'fm_value',
                    'sm_value',
                    'ec1_value',
                    'ec2_value',
                    'ec3_value',
                    'ec4_value',
                    'water_flow_2_value',
                    'water_temp_2_value',
                    'cs2_value',
                    'cdc2_value',
                    'cmp1a_value',
                    'sc_pressure_value',
                    'alert_analysis_complete',
                ],
                { table: pg_tables.ge.mm3 }
            ),
            mm4: new pgp.helpers.ColumnSet(
                [
                    // 'id',
                    'capture_datetime',
                    'system_id',
                    'host_date',
                    'host_time',
                    'host_datetime',
                    'he_level_value',
                    'water_flow_value',
                    'water_temp_value',
                    'shield_si410_value',
                    'recon_ruo_value',
                    'recon_si410_value',
                    'coldhead_ruo_value',
                    'he_pressure_value',
                    'case_temp_value',
                    'cdc1_value',
                    'alert_analysis_complete',
                ],
                { table: pg_tables.ge.mm4 }
            ),
        },
        siemens: {
            default: new pgp.helpers.ColumnSet(
                [
                    // 'id',
                    'capture_datetime',
                    'system_id',
                    'msup_metadata',
                    'or_dash_code',
                    'or_code',
                    'field_current_value',
                    'host_time',
                    'host_date',
                    'host_datetime',
                    'sup_time',
                    'test_time',
                    'lvqd',
                    'msup_sn',
                    'msup_rev',
                    'magnet_sn',
                    'magnet_rev',
                    'he_params',
                    'he_param_1',
                    'he_param_2',
                    'he_alarm_low_value',
                    'he_alarm_high_value',
                    'he_warn_low_value',
                    'he_warn_high_value',
                    'he_level_1_value',
                    'he_level_2_value',
                    'he_status',
                    'eis_status',
                    'field',
                    'self_test_result',
                    'battery_status',
                    'sh_status',
                    'battery_volts_value',
                    'press_htr_status',
                    'press_htr_value',
                    'compressor_status',
                    'compressor_value',
                    'press_sw_status',
                    'cold_head_sensor_1_value',
                    'cold_head_status',
                    'shield_link_value',
                    'shield_bore_value',
                    'shield_sensor_1_value',
                    'shield_sensor_2_value',
                    'shield_status',
                    'turret_sensor_1_value',
                    'turret_sensor_2_value',
                    'turret_status',
                    'ccr_sensor_1_value',
                    'ccr_sensor_2_value',
                    'ccr_1_2_status',
                    'ccr_sensor_3_value',
                    'ccr_sensor_4_value',
                    'ccr_3_4_status',
                    'carbon_r_sensor_1_value',
                    'carbon_r_sensor_2_value',
                    'carbon_r_1_2_status',
                    'carbon_r_sensor_3_value',
                    'carbon_r_sensor_4_value',
                    'carbon_r_3_4_status',
                    'swt_htr_res_1_value',
                    'swt_htr_res_1_status',
                    'quh_htr_res_1_value',
                    'quh_htr_res_2_value',
                    'quh_htr_status',
                    'mag_psia_value',
                    'mag_psia_status',
                    'avg_power_value',
                    'avg_power_status',
                    'epm_status',
                    'erdu_status',
                    'erdu_buttons_value',
                    'erdu_1_status',
                    'erdu_2_status',
                    'erdu_3_status',
                    'tests',
                    'ibutton_sn',
                    'alert_analysis_complete',
                ],
                { table: pg_tables.siemens.default }
            ),
            non_tim: new pgp.helpers.ColumnSet(
                [
                    // 'id',
                    'capture_datetime',
                    'system_id',
                    'msup_metadata',
                    'host_time',
                    'host_date',
                    'host_datetime',
                    'rx',
                    'tx',
                    'he_params',
                    'he_param_1',
                    'he_param_2',
                    'he_alarm_low_value',
                    'he_alarm_high_value',
                    'he_warn_low_value',
                    'he_warn_high_value',
                    'he_level_1_value',
                    'out_measure_status',
                    'sys_in_msg_sys_status',
                    'sys_pwr_fail',
                    'bat_out_erdu_bat_status',
                    'shield_out_fridge_status',
                    'shield_temp_value',
                    'shield_fridge_alarm_value',
                    'shield_fridge_warn_value',
                    'scru_out_eis_status',
                    'scru_in_msg_eis_status',
                    'emg_rd_in_msg_htr_status',
                    'in_msg_switch_status',
                    'cca_cab_out_air_con_status',
                    'cca_cab_temp_value',
                    'cca_cab_temp_alarm_value',
                    'cca_cab_temp_warn_value',
                    'gpa_cab_temp_value',
                    'gpa_cab_temp_alarm_value',
                    'gpa_cab_temp_warn_value',
                    'tests_in_mgs_fridge_status',
                    'tests_in_mgs_alarm_status',
                    'tests_in_erdu_load_status',
                    'shim_1_amps_value',
                    'shim_1_volts_value',
                    'shim_1_power_value',
                    'shim_1_status',
                    'shim_2_amps_value',
                    'shim_2_volts_value',
                    'shim_2_power_value',
                    'shim_2_status',
                    'shim_3_amps_value',
                    'shim_3_volts_value',
                    'shim_3_power_value',
                    'shim_3_status',
                    'shim_4_amps_value',
                    'shim_4_volts_value',
                    'shim_4_power_value',
                    'shim_4_status',
                    'shim_5_amps_value',
                    'shim_5_volts_value',
                    'shim_5_power_value',
                    'shim_5_status',
                    'dc_value',
                    'watts_value',
                    'alert_analysis_complete',
                ],
                { table: pg_tables.siemens.non_tim }
            ),
        },
    },
    edu: {
        v2: new pgp.helpers.ColumnSet(
            [
                // 'id',
                'capture_datetime',
                'system_id',
                'temp_probe_0_value',
                'temp_probe_1_value',
                'room_humidity_value',
                'room_temp_value',
                'comp_vib_status',
                'alert_analysis_complete',
            ],
            { table: pg_tables.edu.v2 }
        ),
        v1: new pgp.helpers.ColumnSet(
            [
                // 'id',
                'capture_datetime',
                'system_id',
                'room_humidity_value',
                'room_temp_value',
                'room_head_index_value',
                'temp_probe_1_value',
                'temp_probe_2_value',
                'water_flow_rate_value',
                'current_sensor_adc_value',
                'current_sensor_volts_value',
                'current_sensor_amps_value',
            ],
            { table: pg_tables.edu.v1 }
        ),
    },
};

module.exports = { pg_tables, pg_column_sets };
